
<script type="text/javascript">
var HFApp = {
		appId: "{%$appId%}",
		appHost: "{%$hostUrl%}",

		loadHtml: function(url, method, pardata, dataType, id) {//require jquery api support
			if (!method) { //("POST"  or  "GET")
				method = 'GET';
			}
			if (!dataType) {//xml
				dataType = "text";
			}
			$.ajax({
                type: method,
                url: url,
                data: pardata,
                dataType: dataType,
                success: function(resp){
                	$("#" + id).html(resp);
                }
	 		});
		}
	}

	var connectSnsplus = "{% $connectSnsplus %}";

    function showFanbox()
    {
        $("#fanbox").toggle('fast');
    }


    /* about gift page -S */
    function showGift()
    {
    	if ($("#divGiftFrame").html() == '') {
    		topGift();
    	}
    	$("#giftBox").toggle('fast');
    }

    function topGift()
    {
    	var url = HFApp.appHost + "/gift/top";

		if (connectSnsplus == '') {
			var pardata = {};
		} else {
			var pardata = {'entrance' : 'connect'};
		}

		HFApp.loadHtml(url, 'POST', pardata, 'text', 'divGiftFrame');
    }

    function getGift(connectSnsplus)
    {
    	var url = HFApp.appHost + "/gift/get";

		if (connectSnsplus == '') {
			var pardata = {};
		} else {
			var pardata = {'entrance' : 'connect'};
		}

		HFApp.loadHtml(url, 'POST', pardata, 'text', 'divGiftFrame');
    }

    function postGift()
    {
    	var url = HFApp.appHost + "/gift/post";

		if (connectSnsplus == '') {
			var pardata = {};
		} else {
			var pardata = {'entrance' : 'connect'};
		}

		HFApp.loadHtml(url, 'POST', pardata, 'text', 'divGiftFrame');
    }

    function friendsGift(tid, gid)
    {
    	var url = HFApp.appHost + "/gift/friends";

		if (connectSnsplus == '') {
			var pardata = {'tid' : tid, 'gid' : gid};
		} else {
			var pardata = {'tid' : tid, 'gid' : gid, 'entrance' : 'connect'};
		}

		HFApp.loadHtml(url, 'POST', pardata, 'text', 'divGiftFrame');
    }

    function showGiftLogPost(page)
    {
    	var url = HFApp.appHost + "/gift/post";

		if (connectSnsplus == '') {
			var pardata = {'page' : page};
		} else {
			var pardata = {'entrance' : 'connect', 'page' : page};
		}

		HFApp.loadHtml(url, 'POST', pardata, 'text', 'divGiftFrame');
    }

    function showGiftLogGet(page)
    {
    	var url = HFApp.appHost + "/gift/get";

		if (connectSnsplus == '') {
			var pardata = {'page' : page};
		} else {
			var pardata = {'entrance' : 'connect', 'page' : page};
		}

		HFApp.loadHtml(url, 'POST', pardata, 'text', 'divGiftFrame');
    }
    /* about gift page -E */


    function showInvite(connectSnsplus)
    {
    	if ($("#divInviteFrame").html() == '') {
    		var url = HFApp.appHost + "/invite/top";

    		if (connectSnsplus == '') {
    			var pardata = {};
    		} else {
    			var pardata = {'entrance' : 'connect'};
    		}

    		HFApp.loadHtml(url, 'POST', pardata, 'text', 'divInviteFrame');
    	}
    	$("#inviteBox").toggle('fast');
    }

    function showPay()
    {
    	if ($("#divPayFrame").html() == '') {
    		//topPay(connectSnsplus);
    	}
    	$("#payBox").toggle('fast');
    }

    function topPay()
    {
		var url = HFApp.appHost + "/pay/top";

		if (connectSnsplus == '') {
			var pardata = {};
		} else {
			var pardata = {'entrance' : 'connect'};
		}

		HFApp.loadHtml(url, 'POST', pardata, 'text', 'divPayFrame');
    }

    function payLog()
    {
    	var url = HFApp.appHost + "/pay/log";

		if (connectSnsplus == '') {
			var pardata = {};
		} else {
			var pardata = {'entrance' : 'connect'};
		}

		HFApp.loadHtml(url, 'POST', pardata, 'text', 'divPayFrame');
    }

    function paySystem()
    {
    	var url = HFApp.appHost + "/pay/system";

		if (connectSnsplus == '') {
			var pardata = {};
		} else {
			var pardata = {'entrance' : 'connect'};
		}

		HFApp.loadHtml(url, 'POST', pardata, 'text', 'divPayFrame');
    }

    function consGold(prev)
    {
    	var url = HFApp.appHost + "/consumelogs/gold";

		if (connectSnsplus == '') {
			var pardata = {'prev' : prev};
		} else {
			var pardata = {'entrance' : 'connect', 'prev' : prev};
		}

		HFApp.loadHtml(url, 'POST', pardata, 'text', 'divPayFrame');
    }

    function consCoin()
    {
    	var url = HFApp.appHost + "/consumelogs/coin";

		if (connectSnsplus == '') {
			var pardata = {};
		} else {
			var pardata = {'entrance' : 'connect'};
		}

		HFApp.loadHtml(url, 'POST', pardata, 'text', 'divPayFrame');
    }

	function goToPaySNS()
	{
		var url = HFApp.appHost + "/pay/pay";

		if (connectSnsplus == '') {
			var pardata = {};
		} else {
			var pardata = {'entrance' : 'connect'};
		}

		HFApp.loadHtml(url, 'POST', pardata, 'text', 'divPayFrame');
	}

	function goToPay()
	{
		var url = HFApp.appHost + "/pay/pay";

		if (connectSnsplus == '') {
			var pardata = {};
		} else {
			var pardata = {'entrance' : 'connect'};
		}

		HFApp.loadHtml(url, 'POST', pardata, 'text', 'divPayFrame');
	}

    function initGameOther()
    {
    	//console.debug('init game other');
	    $("#mnuInviteCls,#mnuGift,#mnuGiftCls,#mnuPay,#mnuPayCls").unbind('click');
	    $("#mnuInviteCls").click(showInvite);
	    $("#mnuGift").click(showGift);
	    $("#mnuGiftCls").click(showGift);
	    $("#mnuPay").click(showPay);
	    $("#mnuPayCls").click(showPay);
	    //$("#slider").html('<ul><li style="display:inline"><a href="#"><img src="{%$staticUrl%}/apps/island/images/slider/newitem-20110718-1.jpg" style="display:none;"/></a></li><li style="display:inline"><a href="#"><img src="{%$staticUrl%}/apps/island/images/slider/newitem-20110718-1.jpg" style="display:none;"/></a></li></ul>');
	    //$("#slider").flashSlider({controlsShow: false,vertical: true, speed: 1500, pause: 6000});
	    //$("#extfrmRank").html('<iframe src="http://game.weibo.com/home/widget/box?box=friend&appId=401380203&width=760&title=%E6%8E%92%E8%A1%8C%E6%A6%9C&select=2" width="760" height="186" frameborder="no"></iframe>');
    }

	$(document).ready(function() {
		if (typeof(IS_INDEX_PAGE) == "undefined") {
			initGameOther();
		}
	});
</script>