<link href="{%$staticUrl%}/apps/island/css_2011041102.css?v=1.02" rel="stylesheet" type="text/css" />
<link href="{%$staticUrl%}/apps/island/css_gift.css?v=1.17" rel="stylesheet" type="text/css" />
<style type="text/css">
<!--
a img,:link img,:visited img {
	border: 0 none;
}
-->
</style>

<div class="main" style="height:700px;">
<div class="bg">
<div class="sl01-bg01"></div>
<div class="sl01-bg02">
<div class="sl01-bg02-1 left"></div>
<div class="sl01-bg02-2 left"><a href="javascript:void(0);" onclick="topGift();"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01_03-2.gif" alt="贈送禮物" border="0" /></a></div>
<div class="sl01-bg02-3 left"><a href="javascript:void(0);" onclick="getGift();"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01_04.gif" alt="收到的禮物" border="0" /></a></div>
<div class="sl01-bg02-4 left"><a href="javascript:void(0);" onclick="postGift();"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01_05-2.gif" alt="送出的禮物" border="0" /></a></div>

<div class="sl01-bg02-5 left"></div>
<div class="sl01-bg02-6 left"></div>
</div>
<div class="sl02-bg03"></div>
<div class="sl02-bg04">
	<div style="width:623px; height:390px;">
		<table width="435" border="0" cellpadding="0" cellspacing="0" class="sl02-table01">
		  <tr height="23">
		    <td width="33"></td>
		    <td width="140"><font color="#ff5677">時間</font></td>
		    <td width="80"><font color="#ff5677">好友</font></td>
		
		    <td width="100"><font color="#ff5677">贈送的禮物</font></td>
		    <td width="80"><font color="#ff5677">花費寶石</font></td>
		  </tr>
		</table>
		<table width="435" border="0" cellpadding="0" cellspacing="0" class="sl02-table02">
			<tr height="5"></tr>
		  	{% foreach from=$gift_list item=data_2 key=key_2 %}
		  	<tr>
		    	<td width="33"><img src="{%$staticUrl%}/apps/island/images/gift2/sl02_dian.gif" width="19" height="19" /></td>
		    	<td width="140"><font color="#4986d9">{%$data_2.create_time|date_format:"%Y/%m/%d"%}</font></td>
		
		    	<td width="80"><font color="#4986d9">{%$data_2.to_name%}</font></td>
		    	<td width="100" class="green1" >{%$data_2.name%}</td>
		    	<td width="80"><font color="#4986d9">{%if $data_2.gtype == 1%}免費{%else%}{%$data_2.price%}寶石{%/if%}</font></td>
		  	</tr>
		  	{% /foreach %}
		</table>
	</div>
</div>
<div class="sl01-bg07">
	<div class="sclw left"></div>
	<div class="sl02-zx left">
		{% if $pages > 1 %}
			{%section name=loop loop=$pages %} 
			<a href="javascript:void(0);" onclick="showGiftLogPost({%$smarty.section.loop.index+1%});">{% $smarty.section.loop.index+1 %}&nbsp;</a>
			{%/section%}
		{% /if %}
	</div>
</div>
<div class="sl01-bg08"></div>
</div>
</div>