<link href="{%$staticUrl%}/apps/island/css_2011041102.css?v=1.02" rel="stylesheet" type="text/css" />
<link href="{%$staticUrl%}/apps/island/css_gift.css?v=1.17" rel="stylesheet" type="text/css" />
<style type="text/css">
<!--
a img,:link img,:visited img {
	border: 0 none;
}
-->
</style>

<div class="main">
<div class="bg">
	<div class="sl01-bg01"></div>
	<div class="sl01-bg02">
		<div class="sl01-bg02-1 left"></div>
		<div class="sl01-bg02-2 left"><a href="javascript:void(0);" onclick="topGift();");"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01_03.gif" alt="赠送礼物" border="0" /></a></div>
		<div class="sl01-bg02-3 left"><a href="javascript:void(0);" onclick="getGift();"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01_04.gif" alt="收到的礼物" border="0" /></a></div>
		<div class="sl01-bg02-4 left"><a href="javascript:void(0);" onclick="postGift();"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01_05.gif" alt="送出的礼物" border="0" /></a></div>
		<div class="sl01-bg02-5 left"></div>
		<div class="sl01-bg02-6 left"></div>
	</div>

	<div class="sl01-bg03">
		<span id="test_msg"></span>
		<div class="sl01-li" id="img1">
			<div class="liwu-cz right"><a href="javascript:void(0);" onclick="goPayGift();"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-cz.gif" alt="充值" border="0" /></a></div>
			<div class="liwu-bss right"> 餘額：{%$userGold%}寶石 </div>
			<div class="liwu-bt right" style="padding-left:15px;"><a href="javascript:void(0);" onclick="showType(2)"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-sclw.gif"  alt="收费礼物" border="0" /></a></div>
			<div class="liwu-bt right"><a href="javascript:void(0);" onclick="showType(1)"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-mflw.gif"  border="0" /></a></div>
		</div>
		<div class="sl01-li" id="img2" style="display:none">
			<div class="liwu-cz right"><a href="javascript:void(0);" onclick="goPayGift();"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-cz.gif" alt="充值" border="0" /></a></div>
			<div class="liwu-bss right"> 餘額：{%$userGold%}寶石</div>
			<div class="liwu-bt right" style="padding-left:15px"><a href="javascript:void(0);" onclick="showType(2)"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-sclw-2.gif"  alt="收费礼物" border="0" /></a></div>
			<div class="liwu-bt right"><a href="javascript:void(0);" onclick="showType(1)"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-mflw-2.gif"  border="0" /></a></div>
		</div>
		<div class="sl01-li" id="img3" style="display:none">
			<div class="liwu-cz right"><a href="javascript:void(0);" onclick="goPayGift();"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-cz.gif" alt="充值" border="0" /></a></div>
			<div class="liwu-bss right"> 餘額：{%$userGold%}寶石 </div>
			<div class="liwu-bt right" style="padding-left:15px"><a href="javascript:void(0);" onclick="showType(2)"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-sclw.gif"  alt="收费礼物" border="0" /></a></div>
			<div class="liwu-bt right"><a href="javascript:void(0);" onclick="showType(1)"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-mflw-2.gif"  border="0" /></a></div>
		</div>
		<div class="sl01-li" id="img4" style="display:none">
			<div class="liwu-cz right"><a href="javascript:void(0);" onclick="goPayGift();"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-cz.gif" alt="充值" border="0" /></a></div>
			<div class="liwu-bss right"> 餘額：{%$userGold%}寶石 </div>
			<div class="liwu-bt right" style="padding-left:15px"><a href="javascript:void(0);" onclick="showType(2)"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-sclw.gif"  alt="收费礼物" border="0" /></a></div>
			<div class="liwu-bt right"><a href="javascript:void(0);" onclick="showType(1)"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-mflw-2.gif"  border="0" /></a></div>
		</div>
		<div class="sl01-li" id="img5" style="display:none">
			<div class="liwu-cz right"><a href="javascript:void(0);" onclick="goPayGift();"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-cz.gif" alt="充值" border="0" /></a></div>
			<div class="liwu-bss right"> 餘額：{%$userGold%}寶石 </div>
			<div class="liwu-bt right" style="padding-left:15px"><a href="javascript:void(0);" onclick="showType(2)"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-sclw.gif"  alt="收费礼物" border="0" /></a></div>
			<div class="liwu-bt right"><a href="javascript:void(0);" onclick="showType(1)"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-mflw-2.gif"  border="0" /></a></div>
		</div>
	</div>

	<input type="hidden" id="tid" name="tid" value="1" />
	<input type="hidden" id="gid" name="gid" value="1" />
	<input type="hidden" name="gift_value" id="gift_value" value="0" />
	<input type="hidden" name="histroy_value"  id="histroy_value" value="1" />

	<div class="sl01-bg04" id="type_1">
	{% foreach from=$giftFrees item=data_1 key=key_1%}
		<div class="liwu-ul" id="tab{%$key_1%}" style="padding-left:0px">
			<div style="padding-left:90px">
				{% foreach from=$data_1 item=data key=key %}
				<div class="mflw-li left" style="margin-bottom:20px">
					<div class="liwu-img right"><img src="{%$staticUrl%}/apps/island/images/gift/items/{%$data.img%}?v=20101208" width="100" height="100" /></div>
					<div class="liwu-txt right">{%$data.name%}<br /><br />
					{% if $userLevel >= $data.level %}
						<input type="hidden" name="MfcanSend" id="MfcanSend" value="-1" />
						<input type="radio" name="rdoGift" onclick="setGiftValue(0,{%$data.gid%});" value="{%$data.gid%}" />
					{%else%}
						<span style="color: red;">{%$data.level%}級后可以贈送</span>
					{%/if%}
					</div>
				</div>
				{% /foreach %}
			</div>
		</div>
	{% /foreach %}
	</div>

	<div class="sl01-bg04" id="type_3" style="display:none;">
		<div class="liwu-ul"></div>
	</div>

	<div class="sl01-bg04" id="type_2">
		{% foreach from=$giftCharges item=data_2 key=key_2 %}
		<div class="liwu-ul" id="tab_2{%$key_2%}" style="padding-left:0px"><div style="padding-left:90px">
			{% foreach from=$data_2 item=data key=key %}
				<div class="sflw-li left" style="margin-bottom:20px">
					<div class="liwu-img right"><img src="{%$staticUrl%}/apps/island/images/gift/items/{%$data.img%}" width="100" height="100" /></div>
					<div class="liwu-txt2 right">價格：{%$data.price%}寶石<br />{%$data.name%}<br />
			  			{% if $userLevel >= $data.level %}
			  			<input type="hidden" name="canSend" id="canSend" value="-1" />
							<label>
								<input type="hidden" name="value_{%$data.gid%}" id="value_{%$data.gid%}" value="{%$data.price%}" />
								<input type="radio" name="rdoGift" onClick="setGiftValue({%$data.price%},{%$data.gid%})" value="{%$data.gid%}" />
							</label>
						{%else%}
							<span style="color: red;">{%$data.level%}級后可以贈送</span>
						{%/if%}
					</div>
				</div>
			{% /foreach %}
			</div>
		</div>
		{% /foreach %}
	</div>

	<div class="sl01-bg04_1" id="type_4">
		<div class="liwu-ul" style="padding-left:70px;padding-top:140px;text-align:center;font-size:14px;height:200px;color:#ff0000;">
		  <p>你的寶石不夠哦，建議您<a href="javascript:void(0);" onclick="goPayGift();"><b>馬上儲值</b></a><br/><br/></p>
		  <p><a href="javascript:void(0)"><img src="{%$staticUrl%}/apps/island/images/gift2/fhyx.gif" style='cursor:hand' onclick="goback()" border="0" /></a></p>
		</div>
	</div>
	<div class="sl01-bg04_1" id="type_5">
		<div class="liwu-ul" style="padding-left:70px;padding-top:140px;text-align:center;font-size:14px;height:200px;color:#ff0000;">
		  <p>免費禮物一天只能發送三次<br/>建議您發送<a href='javascript:void(0);' onclick="showType(2);"><b>收费礼物</b></a>给你的好友</p>
		  <p><a href="javascript:void(0)"><img src="{%$staticUrl%}/apps/island/images/gift2/fhyx.gif" style='cursor:hand' onclick="goback()" border="0" /></a></p>
		</div>
	</div>

	<div class="sl01-bg07">
		<div class="sclw left" id="dosubmit1"><a onclick="doSubmit(1)"><img src="{%$staticUrl%}/apps/island/images/gift2/sclw.gif" border="0" style="cursor:pointer ;" /></a></div>
		<div class="sclw left" id="dosubmit2"><a onclick="doSubmit(2)"><img src="{%$staticUrl%}/apps/island/images/gift2/sclw.gif" border="0" style="cursor:pointer ;" /></a></div>
		<div class="sclw left" id="dosubmit3" style="display: none;"><a onclick="doSubmit(3)"><img src="{%$staticUrl%}/apps/island/images/gift2/sclw.gif" border="0" /></a></div>
		<div class="sclw left" id="dosubmit4"></div>
		<div class="sclw left" id="dosubmit5"></div>

		<div class="sl02-zx left" id="page_1">{% foreach from=$giftFrees item=data_1 key=key_1 %}<a href="javascript:void(0);" id="pag1_{%$key_1%}" class="cur_cls" onclick="showTab({%$key_1%})">{%$key_1+1%}&nbsp;</a>{% /foreach %}</div>
		<div class="sl02-zx left" id="page_2">{% foreach from=$giftCharges item=data_1 key=key_1 %}<a href="javascript:void(0);" id="pag2_{%$key_1%}" class="cur_cls" onclick="showTab_2({%$key_1%})">{%$key_1+1%}&nbsp;</a>{% /foreach %}</div>
		<div class="sl02-zx left" id="page_3"></div>
		<div class="sl02-zx left" id="page_4"></div>
		<div class="sl02-zx left" id="page_5"></div>
	</div>
	<div class="sl01-bg08"></div>
</div>
<script type="text/javascript">
	var user_gold = "{%$userGold%}";
	var site_url = '{%$staticUrl%}';
	var gift_value = 0;
	var count = '{%$count%}';

	function doSubmit(i) {
		switch(i) {
			case 1:
				var MfcanSend = $('#MfcanSend').val();
				if(MfcanSend != 1) {
					return false;
				}
			break;
			case 2:
				$('#histroy_value').val(2);
				gift_value = $('#gift_value').val();

				var canSend = $('#canSend').val();
				if( canSend != 1 ) {
					return false;
				}
	     	break;
			case 3:
				gift_value = $('#gift_value').val();
				$('#histroy_value').val(3);
			break;
		}

		if(i != 1) {
			if(parseInt(gift_value) == '0') {
	        	return false;
			}

	     	else if(parseInt(gift_value) > parseInt(user_gold)) {
	       		showType(4);
	       		return false;
	     	}
		} else {
			if(count <= 0) {
				showType(5);
				return false;
			}
		}

		var tid = $('#tid').val();
		var gid = $('#gid').val();
		
		friendsGift(tid, gid);
		return false;
	}

	function goback() {
		var histroyid = $('#histroy_value').val();
		showType(parseInt(histroyid));
	}

	function setGiftValue(price,cid)
	{
		if (price > 0) {
			$('#gift_value').val(price);
			$('#canSend').val(1);
		} else {
			MfSend();
		}

		$('#gid').val(cid);
	}

	function MfSend() {
		$('#MfcanSend').val(1);
	}

	function showTab(j) {
		var k = {% $freeCount %};
		var i = 0;
	
		for(i=0; i<k; i++) {
			if(i == j) {
				$('#tab'+i).show();
				$('#pag1_'+i).css('className', 'cur_cls2');
			} else {
				$('#tab'+i).hide();
				$('#pag1_'+i).css('className', 'cur_cls');
			}
		}
	}

	function showTab_2(j) {
		var k = {%$chargeCount%};
		var i = 0;

		for(i=0; i<k; i++) {
			if(i == j) {
				$('#tab_2'+i).show();
			} else {
				$('#tab_2'+i).hide();
			}
		}
	}

	function showType(j) {
		var k = 5;

		$("#tid").val(j);

		for(i=1; i<=k; i++) {
			if(i == j) {
				$('#type_'+i).show();
				$('#page_'+i).show();
				$('#dosubmit'+i).show();
				$('#img'+i).show();
			} else {
				$('#type_'+i).hide();
				$('#page_'+i).hide();
				$('#dosubmit'+i).hide();
				$('#img'+i).hide();
			}
		}
	}

	function goPayGift()
	{
		goPay();
		showGift();
		return;
	}
	
	showTab(0);
	showTab_2(0);
	showType({%$cid%});
</script>
</div>