<div style="margin-left:0px">
<!-- banner iframe -->
</div>

<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
{%include file="cmscript.phtml"%}
<style type="text/css">
<!--
.zleft{ float:left;}
.zclear{ clear:both;}
.bo_1,.bo_2,.bo_3,.bo_4,.bo_5,.bo_6,.bo_7{ padding-right:5px;}
.renwu{ width:750px; height:28px; padding-bottom:2px; background:url({%$staticUrl%}/apps/island/images/guide/bg.gif) no-repeat; width:747px; height:28px; background-color:#d5f9f5;}
.renwu div{ position:relative}
.banner{ padding-bottom:2px;}
div#fanbox {
    background:none repeat scroll 0 0 #FFFFFF;
    border-color:#6D84B4;
    border-style:none solid solid;
    border-width:0 10px 10px;
    left:140px;
    overflow:hidden;
    position:absolute;
    display:none;
    top:110px;
    width:293px;
    height:380px;
}

div#fanbox #fan_title {
    background:none repeat scroll 0 0 #6D84B4;
    border-bottom:1px solid #AAAAAA;
    color:white;
    height:28px;
    line-height:28px;
    overflow:hidden;
    padding:0 10px;
    text-align:right;
}
div#fanbox #fan_title a {
	color:white;
	font-weight:bold;
}
-->
</style>

{% if $pgiftTF eq "0" %}
<div id="percent">
	<div class="renwu">
	{% if $isfanTF eq "0" %}
    <div id="id_complete_isfan" style="position:absolute; left:221px;"><input type="image" src="{%$staticUrl%}/apps/island/images/guide/fan.gif" width="110" height="28" onclick="complete_fan(); return false;" /></div>
	{% /if %}
	</div>
	<div id="fanbox">
    <div id="fan_title"><a href="#" onclick="close_complete_fan();">關閉</a></div>
    {% if $smarty.const.APP_ID==117523854945742 %}
	<iframe src="http://www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2Fapps%2Fapplication.php%3Fid%3D117523854945742&amp;width=292&amp;colorscheme=light&amp;show_faces=true&amp;border_color&amp;stream=false&amp;header=false&amp;height=350" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:292px; height:350px;" allowTransparency="true"></iframe>
	{% elseif $smarty.const.APP_ID==130346993713055 %}
    <iframe src="http://www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2Fapps%2Fapplication.php%3Fid%3D130346993713055&amp;width=292&amp;colorscheme=light&amp;show_faces=true&amp;border_color&amp;stream=false&amp;header=false&amp;height=350" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:292px; height:350px;" allowTransparency="true"></iframe>
    {% else %}
    <iframe src="http://www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2Fapps%2Fapplication.php%3Fid%3D125043264175761&amp;width=302&amp;colorscheme=light&amp;show_faces=true&amp;border_color&amp;stream=false&amp;header=false&amp;height=350" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:302px; height:350px;" allowTransparency="true"></iframe>
    {% /if %}
	</div>
</div>
{% /if %}

<div class="title">
	<div class="menu">
        <ul style="padding-left:150px;width:700px;">
        	<li style="width:76px;"><a href="http://tw.socialgame.yahoo.net/userapp/userapp.php?appid={%$smarty.const.APP_ID%}" target="_top"><img src="{%$staticUrl%}/apps/island/images/menu/v2/home.gif" title="我的小島" alt="我的小島" /></a></li>
        	<li style="width:88px;"><a href="{%$hostUrl%}/invite/top"><img src="{%$staticUrl%}/apps/island/images/menu/v2/invite.gif" title="邀請朋友" alt="邀請朋友" /></a></li>
        	<li style="width:76px;"><a href="{%$hostUrl%}/gift/top"><img src="{%$staticUrl%}/apps/island/images/menu/v2/gift.gif" title="贈送禮物" alt="贈送禮物" /></a></li>
        	<li style="width:89px;padding-top:6px;"><a href="{%$hostUrl%}/pay/top"><img src="{%$staticUrl%}/apps/island/images/menu/v2/pay.gif" title="兌換寶石" alt="兌換寶石" /></a></li>
        	<li style="width:68px;"><a href="http://tw.socialgame.yahoo.net/mtag/mtag.php?ac=home&tagid=104" target="_blank"><img src="{%$staticUrl%}/apps/island/images/menu/v2/forum.gif" title="玩家論壇" alt="玩家論壇" /></a></li>
        	<!-- <li style="width:65px;"><a href="{%$snsUrl%}" target="_blank"><img src="{%$staticUrl%}/apps/island/images/menu/v2/help.gif" title="幫助" alt="幫助" /></a></li> -->
        </ul>
	</div>
</div>
    {% if $showNotice == true %}
	  <div class="guang" style="margin-top:5px;">
    	  <div class="guang_b" style="clear:both;"></div>
    	  <div style="clear:both;"></div>
	  {% foreach from=$mainNotice item=data %}
    	  <div class="zleft guang_z">{%if $data.link%}<a href="{%$data.link%}" target="_blank">[{%$data.create_time|date_format:"%Y-%m-%d"%}]  {%$data.title%}</a>{%else%}[{%$data.create_time|date_format:"%Y-%m-%d"%}]  {%$data.title%}{%/if%}</div>
    	 {% /foreach %}
</div>
{% /if %}
<script src="{%$staticUrl%}/js/jquery.flashSlider-1.0.min.js" type="text/javascript"></script>
<script type="text/javascript">
    /*jQuery(document).ready(function() {
        jQuery("#slider").flashSlider({controlsShow: false,vertical: true, speed: 1500, pause: 6000});
    });*/
</script>