<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>发东西的小宝贝，先凑合着用</title>
<style type="text/css">
.basic-input {
	border: 1px solid #C9C9C9;
	border-bottom-left-radius: 3px 3px;
	border-bottom-right-radius: 3px 3px;
	border-top-left-radius: 3px 3px;
	border-top-right-radius: 3px 3px;
	font-size: 14px;
	height: 15px;
	padding: 5px;
	width: 200px;
}
.detail {
	width:80%;
}
</style>
</head>
<body>
<div id="wrapper">

	<div id="content">
	    <!--  
	    <h1>连续登录查询</h1>
	    -->
		<div class="grid-8-2 clearfix">
	    	<div class="article">
	    	 <span class="pl">{% if $msg %}{% $msg %}{% /if %}</span>
				<form name="frm" method="post" action="{% $hostUrl %}/swh/send" >
				 <table style="margin-bottom:20px;">
			         <tr>
			        <th>小岛门牌号</th>
			        </tr>
			        <tr>
			        <td><textarea rows="5" cols="40" name="uids"></textarea></td>
			        </tr>
			     </table>
			    <span class="pl">* CID 不可重复，如果添加多个用户，用户id之间用逗号（,）隔开</span>
		       	<div style="border-bottom: 1px dashed #D4D4D4;margin:20px 0;"></div>
			        <table>
			        <tr>
			        <td><strong>给用户的feed</strong></td>
			        <td><textarea rows="3" cols="40" name="feed"></textarea></td>
			        </tr>
			        <tr>
			        <td><strong>物品id及数量</strong></td>
			        <td><textarea rows="3" cols="40" name="cids"></textarea>
			                  例如：82431*1,82531*1
			        </td>
			        </tr>
			        <tr>
			        <td><strong>海星数量</strong></td>
			        <td><input type="text" name="star" size="20" /></td>
			        </tr>
			        <tr>
			        <td><strong>金币数量</strong></td>
			        <td><input type="text" name="coin" size="20" /></td>
			        </tr>
					<tr>
			        <td><strong>宝石数量</strong></td>
			        <td><input type="text" name="gold" size="20" /></td>
			        </tr>
			        </table>
			        <input type="submit" value="发放" />
		       	</form>
	    	</div>
	    </div>
	</div>
</div>
</body>
</html>