<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>图鉴后台</title>
</head>
<body>
	<br />
	&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% $hostUrl %}/operate/index"><b>返回首页</b></a>
	<br /><br />
	<div>
		{% foreach from=$datavo item=data %}
		<form action="{%$hostUrl%}/operate/atlasbookupdate" method="post">
			图鉴ID:<input type="text" name="data[id]" size="4" value="{%$data.id%}" />&nbsp;&nbsp;
			名字:<input type="text" name="data[name]" size="15" value="{%$data.name%}" />&nbsp;&nbsp;
			数据:<input type="text" name="data[items]" size="100" value="{%$data.items%}" />&nbsp;&nbsp;
			<input type="submit" value="更新" />
			<br /><br />
		</form>
		{% /foreach %}
	</div><br />
	<form action="{%$hostUrl%}/operate/atlasbookaddnew" method="post">
		<input type="submit" name="add" value="新加一条" />
	</form><br />
	<form action="{%$hostUrl%}/operate/atlasbookdel" method="post">
		<input type="text" size="5" name="id" value="1" />
		<input type="submit" name="del" value="删除勋章" />(输入勋章ID)
	</form>
</body>
</html>