<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>后台工具</title>
</head>
<body>
	<br />
	&nbsp;&nbsp;&nbsp;<span><a href="{% $hostUrl %}/operate/teambuy">团购</a></span>
	&nbsp;&nbsp;&nbsp;<span><a href="{% $hostUrl %}/operate/collectlist">收集</a></span>
	&nbsp;&nbsp;&nbsp;<span><a href="{% $hostUrl %}/operate/atlasbook">图鉴</a></span>
	&nbsp;&nbsp;&nbsp;<span><a href="{% $hostUrl %}/operate/awardconfig">连续登陆</a></span>
	<!-- &nbsp;&nbsp;&nbsp;<span><a href="{% $hostUrl %}/operate/onegold">一元店</a></span>-->
</body>
</html>