<div class="bd">
	<div class="top-nav-info">
	<!--  
	    <a href="http://www.douban.com/doumail/">豆邮</a>
	    <a href="http://www.douban.com/accounts/" target="_blank">lei.wu的帐号</a>
	    <a href="http://www.douban.com/accounts/logout?ck=aVBs">退出</a>
	-->
	</div>

    <div class="top-nav-items">
        <ul>
			<li class="on"><a href="{% $hostUrl %}/whoisgod/">首页</a></li>
        </ul>
    </div>
</div>