<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>快樂島主</title>
<link href="{%$staticUrl%}/apps/island/main_2011041101.css?v=1.01" rel="stylesheet" type="text/css" />
<script src="{%$staticUrl%}/apps/island/js/v1/nav.js?v=1.0" type="text/javascript"></script>
<script src="{%$staticUrl%}/js/hf-report.js?v=1.0" type="text/javascript"></script>
<style type="text/css">
<!--
body{
	overflow-x:hidden;
}

a img,:link img,:visited img {
	border: 0 none;
}

object#swfcontent {
	display: inline;
}

.box {
	border: 1px solid #CCCCCC;
}
-->
</style>
</head>
<body>
<div class="main" style="height:960px;">
{%include file="menu.phtml"%}
	<div id="main_content" style="background-color:#7accef;width:748px;height:600px;">
		<div id="loadingdiv" style="position: absolute; left: 290px; top: 360px;"><img src="{%$staticUrl%}/apps/island/images/common/loading1.gif" title="加載中..." alt="加載中..."/></div>
		<div id="flashdiv"></div>
		<script src="{%$staticUrl%}/js/swfobject.js" type="text/javascript"></script>
		<script type="text/javascript">
			var VIEWER_ID = {%$uid%};
			var OWNER_ID = VIEWER_ID;
			var FIRST_LOGIN = {%$newuser%};
			if (FIRST_LOGIN==1) {
				HFcLoadTm.setNewUser();
			}

			function getCookie(name) {
				var arr = document.cookie.match(new RegExp('(^| )'+name+'=([^;]*)(;|$)'));
				if(arr != null) return unescape(arr[2]); return null;
			}
			var hf_skey = getCookie('hf_skey');
			if (hf_skey) {
	        	var flashVars={"ver":"11","pNum":"11","uid":"{%$uid%}","loadingUi":"{%$staticUrl%}/swf/loadingUi2.swf?v=2011071401", "interfaceUrl":"{%$hostUrl%}/api/initswf?v=2011101501","snsType":"facebook_ft","charge":"1","pic1":"{%$staticUrl%}/html/b/images/load01.jpg","pic2":"{%$staticUrl%}/html/b/images/load02.jpg"};
	        	var params = { base: "{%$staticUrl%}/", allowScriptAccess: "always", menu:"false", wmode: "opaque", allowFullScreen: "true", bgcolor: "#7accef", align: "middle", quality: "high"};
	        	var attrs = { id: "islandLoader", name: "islandLoader" };
	        	swfobject.embedSWF("{%$staticUrl%}/swf/islandLoader.swf?v=2012011702", "flashdiv",  "748", "600", "10.0", "{%$staticUrl%}/expressInstall.swf", flashVars, params, attrs, checkFlashable);
	        } else {
	        	var html = '<div style="padding-top:50px;color:red;font-size:14px;text-align:center;">檢測到您的瀏覽器沒有開啟或接收Cookie！請嘗試開啟后，重新進入。</div>';
	        	$('#flashdiv').html(html);
	        	HFcLoadTm.nocookie();
	        }

			function checkFlashable(res) {
				if (!res.success) {
					var strhtml = '您沒有安裝Adobe Flash Player，或者Flash版本過低，建議安裝10.0以上版本。<br/>請點擊<a href="http://get.adobe.com/cn/flashplayer/" target="_blank">這裡</a>進行安裝。';
					$('#loadingdiv').css('left', '100px').css('top', '250px').css('color', 'red').html(strhtml);
					HFcLoadTm.noflash();
				}
			}

	        function hideLoading()
	        {
	        	$('#loadingdiv').hide();
	        	initGameOther();

	        	HFcLoadTm.flashStartLoad();
	        	if (window.console && console.debug) {
	    			console.debug('startload');
	      		}
	        }

	        function loadCompleted()
	        {
	        	HFcLoadTm.flashFinishLoad();
	        	if (window.console && console.debug) {
	    			console.debug('endload');
	      		}
	        }
		</script>
	</div>
</div>

<script type="text/javascript">
	function goInvite(connect)
	{
		//location.href = '{%$smarty.const.HTTP_PROTOCOL%}apps.facebook.com/{%$smarty.const.APP_NAME%}/invite/top';
		showInvite(connect);
		return false;
	}

	function goPay()
	{
		topPay();
		showPay();
		return;
		//location.href = '{%$smarty.const.HTTP_PROTOCOL%}apps.facebook.com/{%$smarty.const.APP_NAME%}/pay/top';
	}
	function addfans()
	{
		document.getElementById('fanbox').style.display='block';
		document.getElementById('addfans').style.display='block';
	}

	function colsefans()
	{
		document.getElementById('fanbox').style.display='none';
		document.getElementById('addfans').style.display='none';
	}
	function reloadGame()
	{
		top.location.href = '{%$smarty.const.HTTP_PROTOCOL%}apps.facebook.com/{%$smarty.const.APP_NAME%}/';
	}
</script>
{%include file="footer.phtml"%}