<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>捕鱼后台-添加商品</title>
<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
<script>
function checkplant() {
	var id = $("#picpath").val();
	//alert('aa');
	$.ajax({
		 type: "POST",
		 url: "{%$hostUrl%}/mycatchfish/checkplant",
		 data:   "act=checkPlant&itemId="+id,
		 success: function(msg){ alert( msg ); } 
		}); 	
}
</script>
</head>
<body>
	<br />
	<div>
		<form action="{%$hostUrl%}/mycatchfish/product" method="post">
		<table align=center>
			<tr>
				<td>请输入商品ID:</td>
				<td><input type="text" name="pid" value="{%$pid%}"></td>
				<td><input type="submit" name="search" value="查询"></td>
				<td align=left width=400>
				<a href="{%$hostUrl%}/mycatchfish/product">去修改商品</a>
				&nbsp;&nbsp;
				<a href="{%$hostUrl%}/mycatchfish/probability">去修改概率</a>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<a href="{%$hostUrl%}/mycatchfish/stat">去查看统计</a>				
				</td>
			</tr>
		</table>
		<input type="hidden" name="act" value="search">
		</form>
		<table align=center>
			<tr>
				<td height=50>&nbsp;</td>
			</tr>
		</table>
		<form action="{%$hostUrl%}/mycatchfish/addproduct" method="post">		
		  <table border=0 width=75% align=center>
		  	<tr><td align=center colspan=2><font color=red>{%$msg%}</font></td></tr>
		  	
		  	<tr><td width=10% align=center><b>商品ID</b></td><td><input type="text" name="pid" value="{%$newpid%}" style="width:100px;"></td></tr>
		  	<tr><td width=10% align=center><b>建筑名称</b></td><td><input type="text" name="name" value="" style="width:300px;"></td></tr>
			<tr><td width=10% align=center><b>概率</b></td><td><input type="text" name="probability" value="" style="width:300px;">[如：1*25,2*45,3*40,4*30,5*25]</td></tr>
			<tr><td width=10% align=center><b>建筑ID</b></td><td><input type="text" name="picpath" value="" style="width:100px;" id="picpath"><input type="button" id="check" name="check" value="检查数值是否存在" onclick="checkplant();"></td></tr>
			<!--<tr><td width=10% align=center><b>商品链接地址</b></td><td><input type="text" name="url" value="" style="width:600px;"></td></tr>-->
			<!--<tr><td width=10% align=center><b>TPS</b></td><td><input type="text" name="content" value="" style="width:300px;"></td></tr>-->
			<!--<tr><td width=10% align=center><b>标识</b></td><td><input type="text" name="flag" value="">[0-无 1-有宝石 2-包邮 3-宝石加包邮]</td></tr>-->
			<tr><td width=10% align=center><b>上架日期</b></td><td><input type="text" name="date" value="" style="width:100px;">[格式如:20110910]</td></tr>
			
			<tr><td align=left colspan=2 height=30></td></tr>
			<tr><td align=left colspan=2><font color=red><b>为商品添加概率</b></font></td></tr>
			<tr><td align=left colspan=2 height=30></td></tr>
			<tr><td width=10% align=center><b>0-8折数量</b></td><td><input type="text" name="nums" value="" style="width:350px;">如：10,100,200,500,100000,100000,100000,100000,100000     分别代表0-8折的数量</td></tr>
			<tr><td width=10% align=center><b>[领域一]概率</b></td><td><input type="text" name="pros1" value="" style="width:350px;">如：0,0,10,100,200,400,500,600,800     分别代表抽中0-8折的概率</td></tr>
			<tr><td width=10% align=center><b>[领域二]概率</b></td><td><input type="text" name="pros2" value="" style="width:350px;"></td></tr>
			<tr><td width=10% align=center><b>[领域三]概率</b></td><td><input type="text" name="pros3" value="" style="width:350px;"></td></tr>
			<tr><td width=10% align=center><b>[领域四]概率</b></td><td><input type="text" name="pros4" value="" style="width:350px;"></td></tr>
			<tr><td width=10% align=center><b>[领域五]概率</b></td><td><input type="text" name="pros5" value="" style="width:350px;"></td></tr>
			<tr><td align=center colspan=2><input type="submit" name="update" value="添加并更新缓存"></td></tr>
		  </table>
		  <input type="hidden" name="act" value="add">
		  </form>
	</div>
</body>
</html>