<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>捕鱼后台</title>
<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
<script>
function checkplant() {
	var id = $("#picpath").val();
	//alert('aa');
	$.ajax({
		 type: "POST",
		 url: "{%$hostUrl%}/mycatchfish/checkplant",
		 data:   "act=checkPlant&itemId="+id,
		 success: function(msg){ alert( msg ); } 
		}); 	
}
</script>
</head>
<body>
	<br />
	<div>
		<form action="{%$hostUrl%}/mycatchfish/product" method="post">
		<table align=center>
			<tr>
				<td>请输入商品ID:</td>
				<td><input type="text" name="pid" value="{%$pid%}"></td>
				<td><input type="submit" name="search" value="查询"></td>
				<td align=left width=400>
				<a href="{%$hostUrl%}/mycatchfish/addproduct"><font color=red>添加商品</font></a>
				&nbsp;&nbsp;
				<a href="{%$hostUrl%}/mycatchfish/probability">去修改概率</a>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<a href="{%$hostUrl%}/mycatchfish/stat">去查看统计</a>				
				</td>
			</tr>
		</table>
		<input type="hidden" name="act" value="search">
		</form>
		<table align=center>
			<tr>
				<td height=50>&nbsp;</td>
			</tr>
		</table>
		{% if $productinfo.pid>=1 %}	
		<form action="{%$hostUrl%}/mycatchfish/product" method="post">		
		  <table border=0 width=75% align=center>
		  	<tr><td width=10% align=center><b>建筑名称</b></td><td><input type="text" name="name" value="{%$productinfo.name%}" style="width:150px;"></td></tr>
			<tr><td width=10% align=center><b>概率</b></td><td><input type="text" name="probability" value="{%$productinfo.probability%}" style="width:300px;"></td></tr>
			<tr><td width=10% align=center><b>建筑ID</b></td><td><input type="text" name="picpath" value="{%$productinfo.picpath%}" style="width:150px;" id="picpath"><input type="button" id="check" name="check" value="检查数值是否存在" onclick="checkplant();"></td></tr>
			<!--<tr><td width=10% align=center><b>商品链接地址</b></td><td><input type="text" name="url" value="{%$productinfo.url%}" style="width:600px;"></td></tr>-->
			<!--<tr><td width=10% align=center><b>TPS</b></td><td><input type="text" name="content" value="{%$productinfo.content%}" style="width:300px;"></td></tr>-->
			<!--<tr><td width=10% align=center><b>标识</b></td><td><input type="text" name="flag" value="{%$productinfo.flag%}">[0-无 1-有宝石 2-包邮 3-宝石加包邮]</td></tr>-->
			<tr><td width=10% align=center><b>上架日期</b></td><td><input type="text" name="date" value="{%$productinfo.date%}"></td></tr>
			<tr><td align=center colspan=2><input type="submit" name="update" value="修改并更新缓存"></td></tr>
		  </table>
		  <input type="hidden" name="pid" value="{%$productinfo.pid%}">
		  <input type="hidden" name="act" value="update">
		  </form>
		  {% /if %}
	</div>
</body>
</html>