<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>捕鱼排行后台</title>
</head>
<body>
	<br />
	<div>
		<form action="{%$hostUrl%}/mycatchfish/rank" method="post">
		<table align=center>
			<tr>
				<td>请输入日期:</td>
				<td><input type="text" name="date" value="{%$date%}"></td>
				<td><input type="submit" name="search" value="查询"></td>
				<td align=right width=400>
				<a href="{%$hostUrl%}/mycatchfish/probability">去修改概率</a>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<a href="{%$hostUrl%}/mycatchfish/product">去修改商品</a>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<a href="{%$hostUrl%}/mycatchfish/stat">查看统计</a>									
				</td>
			</tr>
		</table>
		<input type="hidden" name="act" value="search">
		</form>
		<table align=center>
			<tr>
				<td height=50>&nbsp;</td>
			</tr>
		</table>
		{% if $list %}
		{% foreach from=$list item=data %}		
		  <table border=0 width=75% align=center>
		  	<tr>
		  	<td width=150 align=center><b>小岛门牌号</b></td><td width=100>{%$data.uid%}</td>
		  	<td width=100 align=center><b>排名</b></td><td>{%$data.rank%}</td>
		  	<td width=100 align=center><b>捕鱼次数</b></td><td>{%$data.num%}</td>
		  	</tr>
		  </table>
		 {% /foreach %} 
		  {% /if %}
	</div>
</body>
</html>