<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>儲值|快樂島主</title>
    <link href="{%$staticUrl%}/apps/island/main_2011041101.css?v=1.01" rel="stylesheet" type="text/css" />
    <link href="{%$staticUrl%}/apps/island/pay_2011031501.css?v=1.00" rel="stylesheet" type="text/css" />
    <style type="text/css">
        html, body { height:100%; }
        body { margin:0; }
    </style>
</head>
<body>
<div class="main">
	{%include file="menu.phtml"%}
	<div>{%$html%}</div>
</div>
</body>
</html>