<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>儲值|快樂島主</title>
    <link href="{%$staticUrl%}/apps/island/main_2011041101.css?v=1.01" rel="stylesheet" type="text/css" />
    <link href="{%$staticUrl%}/apps/island/pay_2011031501.css?v=1.00" rel="stylesheet" type="text/css" />
    <style type="text/css">
        html, body { height:100%; }
        body { margin:0; }
    </style>
    <script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
</head>
<body>
<div class="main">
{%include file="menu.phtml"%}

	<div class="chongzhicontent">
		<img src="{%$user.face%}" width="59" height="60" />
		<div class="xinxi">
			<div class="cname">{%$user.name|escape%}</div>
			<div class="shuzi">寶石： <span style="color:#3c7e9a;font-weight:bold;">{%$user.gold%}</span></div>
			<div class="fhyx"><a href="#" onclick="HFApp.home();"><img style="border:medium none;" src="{%$staticUrl%}/apps/island/images/pay/back.gif" width="80" height="35" /></a></div>
		</div>
	</div>

	<div class="table">
		<ul>
    		<li style="width:50px"></li>
    		<li><a href="{%$hostUrl%}/pay/top"><div class="nav_01">充值寶石</div></a></li>
    		<li><a href="{%$hostUrl%}/pay/log"><div class="nav_02">充值記錄</div></a></li>
    		<li><a href="{%$hostUrl%}/consumelogs/gold"><div class="nav_02">寶石消耗記錄</div></a></li>
			<li><a href="{%$hostUrl%}/consumelogs/coin"><div class="nav_02">金幣消耗記錄</div></a></li>
		</ul>
	</div>

	<div class="content" style="padding-top:10px;padding-left:40px;width:740px;">
		<div style="color:red;padding:0 0 10px 0;">
			<br />
		</div>
		<form id="frmPayOrder" method="get" action="{%$hostUrl%}/pay/pay" style="padding-top:20px">
			<div class="chongzhi" style="margin:40px 0 0 0;">
				<div align="center">
					<p><img src="{%$staticUrl%}/apps/island/images/pay/0_02.gif"  id="dm1" class="diamond" title="兑换100宝石" /><br />
						<input type="submit" name="btnOrder1" id="btnOrder1" value="充值" class="orderbtn" class="diamond" />
					</p>
					<label></label>
				</div>
			</div>
			<div class="chongzhi" style="margin:40px 0 0 0;">
				<div align="center">
					<p><img src="{%$staticUrl%}/apps/island/images/pay/1_02.gif" id="dm2" class="diamond" title="兑换200宝石，送20宝石" /><br />
						<input type="submit" name="btnOrder2" id="btnOrder2" value="充值" class="orderbtn" class="diamond" />
					</p>
					<label></label>
				</div>
			</div>
			<div class="chongzhi" style="margin:40px 0 0 0 ;">
				<div align="center">
					<p><img src="{%$staticUrl%}/apps/island/images/pay/2_02.gif" id="dm3" class="diamond" title="兑换500宝石，送60宝石"/><br />
						<input type="submit" name="btnOrder3" id="btnOrder3" value="充值" class="orderbtn" class="diamond" />
					</p>
					<label></label>
				</div>
			</div>
			<div class="chongzhi" style="margin:40px 0 0 0;">
				<div align="center">
					<p><img src="{%$staticUrl%}/apps/island/images/pay/3_02.gif" id="dm4" class="diamond" title="兑换1000宝石，送140宝石"/><br />
						<input type="submit" name="btnOrder4" id="btnOrder4" value="充值" class="orderbtn" class="diamond" />
					</p>
					<label></label>
				</div>
			</div>
			<!--
			<div class="chongzhi" style="margin:40px 0 0 0;">
				<div align="center">
					<p><img src="{%$staticUrl%}/apps/island/images/pay/4_9.gif" id="dm5" class="diamond" onclick="payOrder('frmPayOrder', 500);" title="兑换5000宝石，送800宝石"/><br />
						价格：500元<br />
						<input type="button" name="btnOrder5" id="btnOrder5" onclick="payOrder('frmPayOrder', 500);" value="充值" class="orderbtn" class="diamond" />
					</p>
					<label></label>
				</div>
				</div>
				-->
		</form>
	</div>


</div>
</body>
</html>