<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
<script src="{%$staticUrl%}/js/jquery.flashSlider-1.0.min.js" type="text/javascript"></script>
<link href="{%$staticUrl%}/apps/island/css_2011041102.css?v=1.01" rel="stylesheet" type="text/css" />
<script src="{%$staticUrl%}/js/cross_domain.js" type="text/javascript"></script>
<style type="text/css">
    html, body { height:100%; }
    body { margin:0; }
</style>

<div class="main">

    <div id="main_content" class="content" style="height:820px;padding-top:2px;">
        <div id="invite_award">
        <table width="748" border="0" cellspacing="0" cellpadding="0">
        	<tr>
        		<td height="39" colspan="5" background="{%$staticUrl%}/apps/island/images/invite/bg_01.gif">
        		<table width="100" border="0" align="right" cellpadding="0" cellspacing="0">
        			<tr>
        				<td></td>
        			</tr>
        		</table>
        		</td>
        	</tr>
        	<tr>
        		<td height="355" width="43" background="{%$staticUrl%}/apps/island/images/invite/bg_02.gif"></td>
        		<td height="355" width="191" background="{%$staticUrl%}/apps/island/images/invite/bg_23.gif"></td>
        		<td height="355" width="315" background="{%$staticUrl%}/apps/island/images/invite/bg_24.gif"></td>
        		<td height="355" width="157" background="{%$staticUrl%}/apps/island/images/invite/bg_25.gif"></td>
        		<td height="355" width="42" background="{%$staticUrl%}/apps/island/images/invite/bg_06.gif"></td>
        	</tr>
        	<tr>
        		<td height="34" width="43" background="{%$staticUrl%}/apps/island/images/invite/bg_07.gif"></td>
        		<td colspan="3" bgcolor="#E5F6FD" align="center">
        			<a href="#" onclick="fbinvite();"><img src="{%$staticUrl%}/apps/island/images/invite/btnInvites.gif" alt="邀請好友" width="152" height="49" border="0" /></a>
        		</td>
        		<td height="34" width="42" background="{%$staticUrl%}/apps/island/images/invite/bg_12.gif"></td>
        	</tr>
        	<tr>
        		<td height="37" colspan="5" background="{%$staticUrl%}/apps/island/images/invite/bg_13.gif"></td>
        	</tr>
        </table>
        </div>
    </div>
</div>

<script type="text/javascript">
  FB.Canvas.setSize();

  function fbinvite() {
	FB.ui(
			    {
				  method: 'apprequests',
				  message: '邀請他們一起來玩吧！',
				  data: 'tracking information for the user',
				  filters: ['app_non_users'],
				  title: '邀請好友'
				},
				function(response) {
						//console.log(response);
					}
		);
	return;
  }
</script>
