<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>

{%include file="teambuy/head.phtml"%}
</head>
<body>
<div class="top-nav">
{%include file="teambuy/topnav.phtml"%}
</div>


<div id="wrapper">
	
	<div id="header"></div>
	<div id="content">
		
		<h1>每次10次，转多少次能转到你指定的物品</h1>
		
    	<div class="grid-16-8 clearfix">
        	<div class="article">
        	
        	<!--  
        	<h2>我回应内容的最新回复&nbsp;·&nbsp;·&nbsp;·&nbsp;·&nbsp;·&nbsp;·</h2>
        	-->
        	
        	<table class="reply_notify">
		    <tbody id="all_bottle">
		    	<tr >
		          <td style="padding-right: 5px;"></td>
		          <td></td>
		        </tr>
			</tbody>
			</table>
			
        	
        	
        	</div>
        	<div class="aside">
        		{%include file="teambuy/right.phtml"%}
        	</div>
        	<div class="extra"></div>
        </div>
	</div>
	
	<div id="footer">
	{%include file="teambuy/footer.phtml"%}
	</div>

</div>


</body>
</html>